// Pune district bounding box used for the placeholder live map
export const PUNE_BOUNDS = {
  minLat: 18.42, maxLat: 18.63,
  minLng: 73.75, maxLng: 73.95,
};

export const DEPARTMENTS = [
  { id: "potholes", name: "Potholes", color: "#C1443A", officerCount: 3 },
  { id: "garbage", name: "Garbage", color: "#4C7A5E", officerCount: 2 },
  { id: "drainage", name: "Drainage", color: "#3D4C6B", officerCount: 2 },
  { id: "streetlights", name: "Streetlights", color: "#E8A33D", officerCount: 2 },
];

// Points of interest used for priority scoring (proximity boosts severity)
export const POIS = [
  { name: "Sassoon General Hospital", type: "hospital", lat: 18.5227, lng: 73.8636 },
  { name: "Wagholi Public School", type: "school", lat: 18.5793, lng: 73.9812 },
  { name: "Fergusson College", type: "college", lat: 18.5236, lng: 73.8393 },
  { name: "PCMC Hospital", type: "hospital", lat: 18.6298, lng: 73.7997 },
];

export const OFFICIALS = [
  { id: "off-1", name: "R. Kulkarni", dept: "potholes", level: 1 },
  { id: "off-2", name: "S. Deshmukh", dept: "garbage", level: 1 },
  { id: "off-3", name: "A. Bhosale", dept: "drainage", level: 1 },
  { id: "off-4", name: "Zonal Officer — East", dept: "potholes", level: 2 },
  { id: "off-5", name: "Divisional Commissioner", dept: "potholes", level: 3 },
];

const now = Date.now();
const hoursAgo = (h) => new Date(now - h * 3600 * 1000).toISOString();

export const SEED_CITIZEN = {
  id: "cit-1",
  name: "Anshul Zalke",
  govId: "GOV-XXXX-1187",
  coins: 240,
  ward: "Wagholi, Pune",
};

export const SEED_COMPLAINTS = [
  {
    token: "CVX-2026-381005",
    category: "garbage",
    title: "Garbage Dump & Solid Waste Heap near Market Road",
    description: "Large uncollected solid waste clutter and waste cart blocking pavement, severe odor and hygiene hazard.",
    severity: 4,
    lat: 18.5520, lng: 73.9350,
    status: "submitted",
    citizenId: "cit-1",
    createdAt: hoursAgo(1),
    lastActionAt: hoursAgo(1),
    escalationLevel: 0,
    assignedOfficerId: "off-2",
    imageUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80",
    audioUrl: "https://actions.google.com/sounds/v1/water/water_bubble.ogg",
    audio_url: "https://actions.google.com/sounds/v1/water/water_bubble.ogg",
    aiDetection: {
      isCivicAnomaly: true,
      category: "garbage",
      damageType: "garbage",
      confidence: 96.2,
      severity: 4,
      labelKey: "ai_garbage_label",
      suggestedTitle: "Garbage Dump & Solid Waste Heap near Market Road",
      estimatedArea: "~3.2m²",
      depthLevel: "Moderate",
      box: { top: 20, left: 16, width: 66, height: 56, label: "garbage 0.96" },
    },
  },
  {
    token: "CVX-2026-000101",
    category: "potholes",
    title: "Deep pothole near Wagholi bus stop",
    description: "Large pothole, water-logged, causing two-wheelers to swerve into traffic.",
    severity: 4,
    lat: 18.5793, lng: 73.9812,
    status: "in_progress",
    citizenId: "cit-1",
    createdAt: hoursAgo(50),
    lastActionAt: hoursAgo(30),
    escalationLevel: 0,
    assignedOfficerId: "off-1",
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    audioUrl: "https://actions.google.com/sounds/v1/water/water_bubble.ogg",
    audio_url: "https://actions.google.com/sounds/v1/water/water_bubble.ogg",
    aiDetection: {
      isCivicAnomaly: true,
      category: "potholes",
      damageType: "pothole",
      confidence: 94.4,
      severity: 4,
      labelKey: "ai_pothole_label",
      suggestedTitle: "Severe road crater / pothole causing vehicle hazard",
      estimatedArea: "~1.8m²",
      depthLevel: "High / Deep",
      box: { x: 20, y: 26, width: 68, height: 54 },
    },
  },
  {
    token: "CVX-2026-000098",
    category: "garbage",
    title: "Overflowing garbage bin, Kharadi lane 4",
    description: "Bin uncollected for over a week, attracting stray animals.",
    severity: 3,
    lat: 18.5515, lng: 73.9345,
    status: "submitted",
    citizenId: "cit-1",
    createdAt: hoursAgo(60),
    lastActionAt: hoursAgo(60),
    escalationLevel: 0,
    assignedOfficerId: "off-2",
    imageUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80",
    aiDetection: {
      isCivicAnomaly: true,
      category: "garbage",
      damageType: "garbage",
      confidence: 92.8,
      severity: 3,
      labelKey: "ai_garbage_label",
      suggestedTitle: "Overflowing municipal garbage container on roadside",
      estimatedArea: "~2.4m²",
      depthLevel: "Moderate",
      box: { x: 18, y: 22, width: 64, height: 52 },
    },
  },
  {
    token: "CVX-2026-000087",
    category: "drainage",
    title: "Blocked drain flooding main road",
    description: "Storm drain blocked with debris, road floods after every rain.",
    severity: 5,
    lat: 18.5227, lng: 73.8636,
    status: "escalated",
    citizenId: "cit-2",
    createdAt: hoursAgo(120),
    lastActionAt: hoursAgo(70),
    escalationLevel: 1,
    assignedOfficerId: "off-3",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18fe2b1?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18fe2b1?auto=format&fit=crop&w=800&q=80",
    aiDetection: {
      isCivicAnomaly: true,
      category: "drainage",
      damageType: "drainage",
      confidence: 95.6,
      severity: 5,
      labelKey: "ai_drainage_label",
      suggestedTitle: "Severely flooded storm drain and waterlogged roadway",
      estimatedArea: "~3.2m²",
      depthLevel: "High / Deep",
      box: { x: 15, y: 20, width: 70, height: 58 },
    },
  },
  {
    token: "CVX-2026-000072",
    category: "potholes",
    title: "Pothole cluster outside Fergusson gate",
    description: "Multiple potholes right at the college gate, high foot traffic.",
    severity: 4,
    lat: 18.5236, lng: 73.8393,
    status: "resolved_pending_validation",
    citizenId: "cit-1",
    createdAt: hoursAgo(200),
    lastActionAt: hoursAgo(4),
    escalationLevel: 0,
    assignedOfficerId: "off-1",
    resolutionNote: "Pothole filled and re-surfaced by PMC road crew on 18 Aug.",
    imageUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    resolutionImageUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=800&q=80",
    aiDetection: {
      isCivicAnomaly: true,
      category: "potholes",
      damageType: "pothole",
      confidence: 89.2,
      severity: 4,
      labelKey: "ai_pothole_label",
      suggestedTitle: "Severe road crater / pothole causing vehicle hazard",
      estimatedArea: "~1.5m²",
      depthLevel: "High / Deep",
      box: { x: 22, y: 28, width: 62, height: 48 },
    },
  },
  {
    token: "CVX-2026-000050",
    category: "potholes",
    title: "Small hairline crack, residential lane",
    description: "Minor road surface crack, low traffic residential lane.",
    severity: 1,
    lat: 18.601, lng: 73.79,
    status: "closed",
    citizenId: "cit-1",
    createdAt: hoursAgo(400),
    lastActionAt: hoursAgo(350),
    escalationLevel: 0,
    assignedOfficerId: "off-1",
    resolutionNote: "Patched by ward maintenance team.",
    citizenSatisfied: true,
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    photoUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    resolutionImageUrl: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=800&q=80",
    aiDetection: {
      isCivicAnomaly: true,
      category: "potholes",
      damageType: "crack",
      confidence: 22.4,
      severity: 1,
      labelKey: "ai_crack_label",
      suggestedTitle: "Road surface alligator cracking observed - preventive seal coating needed",
      estimatedArea: "~0.4m²",
      depthLevel: "Low / Superficial",
      box: { x: 24, y: 32, width: 52, height: 36 },
    },
  },
];

export const SEED_CITIZEN_FLAGS = [
  { citizenId: "cit-2", reason: "3 complaints closed as invalid in 30 days", flagged: true },
];

export const SEED_AUDIT_LOG = [
  { id: 1, actor: "system", action: "Auto-escalated CVX-2026-000087 to Level 1", at: hoursAgo(70) },
  { id: 2, actor: "R. Kulkarni", action: "Marked CVX-2026-000072 as resolved", at: hoursAgo(4) },
  { id: 3, actor: "admin", action: "Reviewed flagged citizen cit-2", at: hoursAgo(20) },
];
